#This is an example of a Azure DevOps pipeline that uses AWS Secrets for FoD authentication
#In this scenerio the FOD client id and client secrets are coming from AWS
#Requires an AWS Service Connection in Azure DevOps
#Changes will need to be made to lines 37-43 in the "SecretsManagerGetSecret@1" task

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: JavaToolInstaller@1
  inputs:
    versionSpec: '21'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'curl -LO https://github.com/fortify/fcli/releases/latest/download/fcli.jar'
  displayName: "Download FCLI"
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'java -jar fcli.jar tool scancentral-client install'
  displayName: "Install ScanCentral Client"

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'java -jar fcli.jar action run package'
  displayName: Package source code


- task: SecretsManagerGetSecret@1
  inputs:
    awsCredentials: '<AWS SERVICE CONNECTION NAME>'
    regionName: '<AWS REGION>'
    secretIdOrName: '<AWS SECRET NAME>'
    variableName: 'FOD_SECRETS'
    logResponse: true

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      CLIENT_ID=$(echo $FOD_SECRETS | jq -r '.FOD_CLIENT_ID')
      CLIENT_SECRET=$(echo $FOD_SECRETS | jq -r '.FOD_CLIENT_SECRET')
      RELEASE=1701735

      java -jar fcli.jar fod session login --url https://ams.fortify.com --client-id $CLIENT_ID --client-secret $CLIENT_SECRET
      java -jar fcli.jar fod sast start -f package.zip --release $RELEASE --store release
      java -jar fcli.jar fod sast wait-for ::release::
      java -jar fcli.jar fod action run check-policy --release $RELEASE
      java -jar fcli.jar fod action run release-summary --release $RELEASE
      java -jar fcli.jar fod session logout
  displayName: "Scan"
      
  env:
    FOD_SECRETS: $(FOD_SECRETS)